-- pega a lista de tabelas que tem relacionamento entre empresa e imposto para utilizars nos avisos de impostos

SELECT R."RDB$RELATION_NAME"
      ,F2."RDB$FIELD_NAME"
      ,F."RDB$FIELD_NAME"      
      ,F3."RDB$FIELD_NAME" 
      ,'SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM '||R."RDB$RELATION_NAME"||' WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL UNION'
  FROM RDB$RELATIONS R
 INNER JOIN RDB$RELATION_FIELDS F2 ON F2."RDB$RELATION_NAME" = R."RDB$RELATION_NAME"
                                  AND F2."RDB$FIELD_NAME" = 'CODIGOEMPRESA'
                                  AND F2."RDB$NULL_FLAG" = 1
 INNER JOIN RDB$RELATION_FIELDS F ON F."RDB$RELATION_NAME" = R."RDB$RELATION_NAME"
                                 AND F."RDB$FIELD_NAME" = 'CODIGOIMPOSTO' 
 INNER JOIN RDB$RELATION_FIELDS F3 ON F3."RDB$RELATION_NAME" = R."RDB$RELATION_NAME"
                                  AND F3."RDB$FIELD_NAME" = 'VARIACAOIMPOSTO'
 ORDER BY R."RDB$RELATION_NAME"

 ------------------------------------------

-- pega a lista de vencimento de impostos de todas as tabelas para enviar os avisos, 

 SELECT GT.CODIGOEMPRESA AS EMPRESA
      ,GT.CODIGOIMPOSTO AS IMPOSTO 
      ,GT.VARIACAOIMPOSTO AS VARIACAO
      ,MAX(IV.VENCIMENTOQUOTA1) AS QUOTA1 
      ,MAX(IV.VENCIMENTOQUOTA2) AS QUOTA2
      ,MAX(IV.VENCIMENTOQUOTA3) AS QUOTA3
      ,CASE WHEN (MAX(IV.VENCIMENTOQUOTA1) BETWEEN CURRENT_DATE AND DATEADD( 30 DAY TO CURRENT_DATE)) THEN
      	MAX(IV.VENCIMENTOQUOTA1)
      ELSE 
      	CASE WHEN (MAX(IV.VENCIMENTOQUOTA2) BETWEEN CURRENT_DATE AND DATEADD( 30 DAY TO CURRENT_DATE)) THEN
	      MAX(IV.VENCIMENTOQUOTA2)
	    ELSE 
	      MAX(IV.VENCIMENTOQUOTA3)
	    END
      END AS VENCIMENTO
      ,I.DESCRIMPOSTO
      ,I.CODIGOGRUPOIMPOSTO AS GRUPO 
      ,IG.DESCRGRUPOIMPOSTO AS DESCRGRUPO
 FROM
(
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFGESTABFPA                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFGESTABFPAHS                 WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFOPIMPOSTO                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFOPIMPOSTOCONTPATRONAL       WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFOPIMPOSTOLR                 WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CFOPIMPOSTOSSIMPLES           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CREDITOINDEVFEDERAL           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CREDITOINDEVGPS               WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM CREDITOINDEVSINDICAL          WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DACCREDITOPERIODO             WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DACOUTRASAPURACOES            WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOESTADUAL                WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOFEDERAL                 WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOFEDERALDARF             WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOFEDERALRETIF            WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOFGTS                    WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOGPS                     WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOMUNICIPAL               WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM DEBITOSINDICAL                WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM EFDINCORPIMOBDEB              WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM EFDINCORPIMOBRET              WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM FUNCCONTRATO                  WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM FUNCCONTRATOHS                WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM FUNCIONARIO                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM GNRESTADUAL                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM GPS                           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM GPSHS                         WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM IMPOSTOCONTROLE               WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM INFORMERENDIMENTOOUTREND      WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM IRRFFOLHA                     WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM NCMIMPOSTOSSIMPLES            WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OBRA                          WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OPCAOFUNRURAL                 WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OPCAOIPI                      WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OPCAOISSQN                    WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OPCAOSIMPLESFEDERAL           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OPCAOSSIMPLESFEDERAL          WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OUTRAAPURACAOICMSDF           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OUTRAAPURACAOICMSPE           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OUTRAEMPEMP                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OUTRAEMPEMPHS                 WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM OUTRAOPERACAOICMSRO           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM PRODUTOIMPOSTOSSIMPLES        WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM PRODUTOIMPOSTOSSIMPLESCFOP    WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM RECEBIMENTO                   WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM TABELACTBFISIMPOSTO           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM TABELAIMPOSTOCTBCTR           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM TOTALICMSPAANEXOS             WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL  UNION
SELECT CODIGOEMPRESA  ,CODIGOIMPOSTO ,VARIACAOIMPOSTO FROM TOTALICMSSCOUTRODEB           WHERE CODIGOIMPOSTO IS NOT NULL AND VARIACAOIMPOSTO IS NOT NULL) GT
INNER JOIN IMPOSTOVENCIMENTO IV ON IV.CODIGOIMPOSTO = GT.CODIGOIMPOSTO 
                               AND IV.VARIACAOIMPOSTO = GT.VARIACAOIMPOSTO
INNER JOIN IMPOSTO I ON I.CODIGOIMPOSTO = IV.CODIGOIMPOSTO
                     AND I.VARIACAOIMPOSTO = IV.VARIACAOIMPOSTO
INNER JOIN IMPOSTOGRUPO IG ON IG.CODIGOGRUPOIMPOSTO = I.CODIGOGRUPOIMPOSTO     
WHERE GT.CODIGOEMPRESA IS NOT NULL
  AND IV.CODIGOIMPOSTO IN (561,2003,2100)
  AND ((IV.VENCIMENTOQUOTA1 BETWEEN CURRENT_DATE AND DATEADD( 60 DAY TO CURRENT_DATE)) or
     (IV.VENCIMENTOQUOTA2 BETWEEN CURRENT_DATE AND DATEADD( 60 DAY TO CURRENT_DATE))or 
     (IV.VENCIMENTOQUOTA3 BETWEEN CURRENT_DATE AND DATEADD( 60 DAY TO CURRENT_DATE)))
GROUP BY GT.CODIGOEMPRESA
      ,GT.CODIGOIMPOSTO 
      ,GT.VARIACAOIMPOSTO
      ,I.DESCRIMPOSTO 
      ,I.CODIGOGRUPOIMPOSTO 
      ,IG.DESCRGRUPOIMPOSTO

---------------------------------------------------------------------------      